// Code generated by wit-bindgen-go. DO NOT EDIT.

package ipnamelookup

import (
	"github.com/bytecodealliance/wasm-tools-go/cm"
	"github.com/mossaka/wasi-http-with-wasm-tools-go/wasi/sockets/network"
	"unsafe"
)

// OptionIPAddressShape is used for storage in variant or result types.
type OptionIPAddressShape struct {
	shape [unsafe.Sizeof(cm.Option[network.IPAddress]{})]byte
}
